config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  get "scout", to: 'pages#scoutinfo', as: 'scoutinfo'
  get "influencer", to: 'pages#influencerinfo', as: 'influencerinfo'
  get 'dashboard', to: 'users#dashboard'

  resources :locations do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: %i[create]
    end
  end

  get 'search', to: "locations#search"

  resources :bookings, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :location
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :reviews
  belongs_to :user
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :location
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :locations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    true
    # devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
skip_before_action :authenticate_user!, only: %i[new create]
  def create
    @booking = authorize Booking.new(booking_params)
    @location = Location.find(params[:location_id])
    @booking.location = @location
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to locations_path
  end

  def booking_params
    params.require(:booking).permit(:date, :location_id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # before_action :set_user
  skip_before_action :authenticate_user!, only: %i[index show]

  def new
    @location = Location.new
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    authorize @location
    if @location.save
      redirect_to @location
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
    @locations = policy_scope(Location).order(created_at: :desc)
    @mlocations = Location.where.not(latitude: nil, longitude: nil)

    @markers = @mlocations.map do |mlocation|
      {
        lng: mlocation.longitude,
        lat: mlocation.latitude,
        infoWindow: { content: render_to_string(partial: "/locations/map_window", locals: { location: mlocation })}
      }
    end
  end

  def search
    @query = params[:query]
    @locations = Location.where("address ILIKE ?", "%#{params[:query]}%")
    @mlocations = @locations.where.not(latitude: nil, longitude: nil)
    @markers = @mlocations.map do |mlocation|
      {
        lng: mlocation.longitude,
        lat: mlocation.latitude,
        infoWindow: { content: render_to_string(partial: "/locations/map_window", locals: { location: mlocation })}
      }
    end
    respond_to do |format|
      format.html { redirect_to locations_path}
      format.js
    end
  end

  def show
    @location = Location.find(params[:id])
    @booking = Booking.new
    authorize @booking
    @markers = [{
        lng: @location.longitude,
        lat: @location.latitude,
        infoWindow: { content: render_to_string(partial: "/locations/map_window", locals: { location: @location })}
      }]
  end

  private

  # def set_location
  #   @location = Location.find(params[:id])
  # end

  def location_params
    params.require(:location).permit(:name, :description, :price, :coordinates, :user_id, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   skip_before_action :authenticate_user!, only: %i[home influencerinfo scoutinfo]
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @location = Location.find(params[:location_id])
    @review = Review.new(review_params)
    @review.location = @location
    if @review.save
      redirect_to location_path(@location)
    else
      render 'location/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def sign_up_params

    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :photo, :is_scout, :location)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @current = current_user
    @locations = policy_scope(Location).order(created_at: :desc)
    authorize @current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Off Trail</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto" rel="stylesheet">
    <%= stylesheet_pack_tag 'map' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for [@user, @location] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address, id: "location_address" %>
    <%= f.input :price %>
    <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :button, type: :submit do %>
    <%= icon('fas', 'check') %>
    <% end %>
  </div>
<% end %>

app/views/locations/_indexcards.html.erb
<!-- <div class="notcontainer"> -->
    <div class="row">
      <% locations.first(10).each do |location| %>
      <div class="col-xs-12 col-sm-6">
        <%if location.photo.present? %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path location.photo, height: 250, width: 300 %>')">
          <% else %>
          <div class="card location-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://source.unsplash.com/random');">
            <% end %>
            <div class="card-category">
              <%= link_to location.name, location_path(location) %>
            </div>
            <div class="card-description">
              <h2>Scout : <%= location.user.first_name.capitalize + " " +location.user.last_name.capitalize %></h2>
              <p>
                <%= location.coordinates %>
              </p>
              <p>$
                <%= location.price %>
              </p>
            </div>
            <%= cl_image_tag location.user.photo, class: "card-user"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <!-- </div> -->

app/views/locations/_map_window.html.erb
<p><%= location.name %></p>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<div class="locations-bg" style="margin-top: 100px;">
  <!-- style search-bar later!!! -->
<div class="search-bar">
  <%= form_tag("/search", method: 'get', remote: true ) do %>
  <%= label_tag(:query, 'Search for:') %>
  <%= text_field_tag(:query)%>
  <span class="btn-search">
  <%= submit_tag("Find") %>
  </span>
  <% end %>
</div>
<!-- ### -->
  <div id="results"></div>
  <div class="map-center">
    <div id="map" style="width: 70%;
          height: 500px;" data-markers="<%= @markers.to_json %>"></div>
  </div>
  <div id="search_results_and_index">
    <%= render 'indexcards', locations: @locations %>
  </div>
  <% if policy(Location).create? %>
  <div class="btn-add">
    <%= link_to new_location_path do %>
    +
    <%end%>
  </div>
  <% end %>
</div>

app/views/locations/new.html.erb
<div class="container">
  <h3 class="newheaderalign" style="font-weight: bold">Add New Location</h3>
  <div class="col-xs-12 col-xs-offset-6 col-md-6 col-md-offset-3" style="margin-top: 40px;">
    <%= render 'form' %>
  </div>
</div>

app/views/locations/search.js.erb
const locations = document.getElementById('search_results_and_index')
locations.innerHTML = '<%= j render "locations/indexcards", locations: @locations, mlocations: @mlocations, markers: @markers %>'

app/views/locations/show.html.erb
<div class="back">
  <div class="container-of-b">
    <div class="b-container">
      <div class="location-info" style="margin-top: 100px;">
          <%= cl_image_tag @location.photo, height: 500, width: 700 , class: "show-image"%>
          <h3><%= @location.name %></h3>
          <p>Scout:
            <%= @location.user.first_name %>
            <%= @location.user.last_name %>
          </p>Description :
          <%= @location.description %>
          <p>Price:
            $
            <%= @location.price %>
          </p>
        </div>
        <div class="btn-actions">
          <%= link_to locations_path do %>
          <%= icon('fas', 'angle-left') %>
          <% end %>
        </div>
    </div>
    <div class="b-container">
      <div
        id="map"
        style="width: 700px;
        height: 500px; margin-top: 100px;"
        data-markers="<%= @markers.to_json %>">
      </div>
      <h3>Book for <%= @location.name %> now!</h3>
      <form action="#">
      <label><p>Pick a date</label></p>
      <input type="date" class="datepicker" >
      </form>
      <button id="myBtn">Book!</button>
    </div>
  </div>
<style>
  .mapboxgl-canvas{
    position: relative !important;
  }
</style>


          <!-- Trigger/Open The Modal -->
<!-- The Modal -->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <div class="modal-info">

        <h3>Your booking is almost done!</h3>
        <h4>Review and pay</h4>
        <hr>
        <p><strong>Name:</strong><%= @location.name %></p>

        <p><strong>Scout:</strong>
            <%= @location.user.first_name %>
            <%= @location.user.last_name %>
        </p>

        <p><strong>Description:</strong><%= @location.description %></p>

        <p><strong>Price:</strong>
            $<%= @location.price %>
        </p>
       <hr>
<div class="inner-date">
  </div>
</div>
    <%= cl_image_tag @location.photo, height: 400, width: 600 , class: "modal-image"%>
        <%= simple_form_for [@location, @booking] do |f| %>
          <%= f.input :date, as: :hidden, id: "date-param" %>
          <%= f.button :submit, "Confirm and pay", class: "my-button" %>

        <% end %>
  </div>


</div>
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
   // step 1. store this inside of a let or const
  // step 2. add some innerhtml // new html tag to the mymodal
  let date = document.querySelector('.selected').getAttribute("aria-label")

  modal.style.display = "block";
  let element = document.querySelector('.inner-date')
  element.innerHTML = '';
  element.insertAdjacentHTML('beforeend', `<p> <strong>Date:</strong> ${date}</p>`);
  let form = document.querySelector('#booking_date');
  form.value = date;
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

app/views/pages/home.html.erb
<%=render "shared/social"%>
<div class="big">
  <div class="banner-home" style="background-image:
         url('<%= cl_image_path 'plane', height: 500, width: 500 %>')">
    <div class="banner-content">
      <div class="site-title">
        <h1>Off Trail</h1>
      </div>
      <!-- add a search bar for explore button here -->
      <div class="btn-explore">
        <%= link_to locations_path do %>
        <%= icon('fas', 'globe') %> Explore now
        <% end %>
      </div>
      <!-- ### -->
      <hr>
      <a href="#jump-info" class="home-down-arrow"><%= icon('fas', 'arrow-down') %></a>
    </div>
  </div>
  <div id="jump-info">
    <div class="grid-home-2x2">
      <div class="scout-title">
        <h3> <%= link_to scoutinfo_path,:class=>"btn-home-join-us" do %>SCOUT<% end %></h3>
        <hr>
        <p>
          Nobody knows your hood better than you... why not get paid for it. Jumpstart your career as a location scout and make some mad moolah.
        </p>
        <br>
        <br>
        <div>
          <%= link_to "Become a Scout", new_user_registration_path,:class=>"btn btn-lg btn-primary" %>
        </div>
      </div>
      <div class="scout-img">
        <img src="https://picsum.photos/600/600" alt="">
        </div>
        <div class="inf-img">
          <%= cl_image_tag 'influencer-2', height: 600, width: 600 %>
          <!-- <img src="https://picsum.photos/500/500" alt=""> -->
        </div>
        <div class="inf-title">
          <h3>
              <%= link_to influencerinfo_path,:class=>"btn-home-join-us" do %>INFLUENCER<% end %></h3>
          <hr>
          <p>As a creator you've got tons on your plate. From creating content, engaging your audience and managing your channel, you're busy AF. We get it. That’s why we created a marketplace that elimates the time wasted scouting locations for your shoot.</p>
          <br>
          <br>
          <div>
            <%= link_to "Become an Influencer", new_user_registration_path,:class=>"btn btn-lg btn-primary" %>
          </div>
        </div>
      </div>
<!--       <div class="footer-home" style="background-image:
         url('<%#= cl_image_path 'leaves', height: 500, width: 500 %>')">
      </div> -->
    </div>
  </div>

app/views/pages/influencerinfo.html.erb
<%=render "shared/social"%>

<div class="banner"  style="background-image:
         url('<%= cl_image_path 'Influencer', height: 500, width: 500 %>')">

<div class="content-card">
  <div class="content">
    <p>rThe domain name info is a generic top-level domain (gTLD) in the Domain Name System (DNS) of the Internet. The name is derived from information, though registration requirements do not prescribe any particular theme.

The info TLD was a response to ICANN's highly publicized announcement,[1] in late 2000, of a phased release of seven new generic top-level do</p>
</div>
</div>
<div class='influencer-button'>
<%= link_to "Become a Influencer", new_user_registration_path,:class=>"btn-home-join-us" %>
</div>
</div>

app/views/pages/scoutinfo.html.erb
<%=render "shared/social"%>

<div class="banner"  style="background-image:
         url('<%= cl_image_path '1-2', height: 500, width: 500 %>')">
<div class="content-card">
  <div class="content">
    <p>rThe domain name info is a generic top-level domain (gTLD) in the Domain Name System (DNS) of the Internet. The name is derived from information, though registration requirements do not prescribe any particular theme.

The info TLD was a response to ICANN's highly publicized announcement,[1] in late 2000, of a phased release of seven new generic top-level do</p>
</div>
</div>
<div class='scout-button'>
<%= link_to "Become a Scout", new_user_registration_path,:class=>"btn-home-join-us" %>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <div class="icon-logo">
    <%= icon('fas', 'crow') %>
    </div>
    <%#= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
       <%= link_to "Explore", locations_path,class: "navbar-wagon-item navbar-wagon-link" %>
    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
            <% end %>

          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Sign up", new_user_registration_path,class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
            <li>
              <%= link_to dashboard_path do %>
                <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
            <% else %>
            <li>
<%= link_to "Sign up", new_user_registration_path,class: "navbar-wagon-item navbar-wagon-link" %>
</li>
<li>
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
</li>

            <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_social.html.erb
<div class="social">
  <ul>
  <li><i class="fab fa-twitter"></i></li>
  <br>
  <li><i class="fab fa-facebook"></i></li>
  <br>
  <li><i class="fab fa-instagram"></i></li>
  <br>
  <li><i class="fab fa-pinterest-p"></i></li>
</ul>
</div>

app/views/users/dashboard.html.erb
    <div class="dashboard-grid">
        <div class="user-info">
            <div class="user-avatar">
                <%= cl_image_tag @current.photo, class: 'img-circle' %>
            </div>
                <div class="user-info-text">
                    <h4><strong><%= @current.first_name + " " + @current.last_name %></strong></h4>
                    <p>
                        <%= @current.location %>
                    </p>
                    <h5><%= @current.is_scout ? "Scout" : "Influencer"%></h5>
                </div>
                <hr>
                <div class="container-actions">
                    <ul>
                        <li>
                            <%= icon('fas', 'cog') %>
                            Settings</li>
                        <li>
                            <%= icon('fas', 'comment') %>
                            Messages</li>
                        <li>
                            <%= icon('fas', 'star') %>
                            Reviews</li>
                    </ul>
                </div>
            </div>

            <div class="user-bookings">
                <!-- ### -->

                <% @current.bookings.each do |booking| %>

                        <div class="db-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                        url('<%= cl_image_path booking.location.photo, width: 450, height: 300 %>');">
                        <div class="container">
                          <h3><strong>Confirmed</strong></h3>
                          <p>Date of departure <%= booking.date %></p>
                            <h2> <%= link_to booking.location.name, location_path(booking.location) %></h2>

                            <h3><%= booking.location.user.first_name %></h3>
                            <p>
                                <%= booking.location.coordinates %>
                            </p>
                            <p>$
                                <%= booking.location.price %>
                            </p>
                            <%= cl_image_tag booking.user.photo, class: 'card-user-d' %>
                    </div>
                    </div>

                    <% end %>
                    <!-- ### -->
            </div>

    <div class="user-bookmarked">
        <% @locations.sample(3).each do |l| %>
        <div class="bookmarked-card">
         <h4><%= l.name %></h4>
          <h5><%= l.description %></h5>
          <%= link_to location_path(l) do %>
          <%= cl_image_tag l.photo, width: 300, height: 200 %>
          <% end %>
        </div>
        <% end %>
    </div>
  </div>
</div>